function pFrontier = plotFrontiers(ah, frontier, x)

f
pFrontier = plot3(ah, x(1,[frontier frontier(1)]), ...
    x(2,[frontier frontier(1)]), ...
    x(3,[frontier frontier(1)]), 'r-',...
    'linewidth',2);
